"""
ENGRAM OS CLI - Export Command

Exports a session as a human-readable markdown report.
Shows all tasks completed, conventions learned, files
modified, and decisions made. Shareable as build log content.

Usage:
    engram export my-auth-service
    engram export my-auth-service --format markdown
    engram export my-auth-service --output ./reports/
"""

import sys
import argparse
import yaml
from pathlib import Path
from datetime import datetime

from engram.cli._display import ok, fail, info, header
from engram.cli._config import SESSIONS_DIR


def export(
    name: str,
    output_dir: str | None = None,
    fmt: str = "markdown"
) -> int:
    """
    Export a session as a shareable report.

    Args:
        name: Session name to export
        output_dir: Output directory
        fmt: Output format (markdown)

    Returns:
        Exit code (0 on success, 1 on failure)
    """
    matches = list(SESSIONS_DIR.glob(f"{name}*.yaml"))
    if not matches:
        fail(f"No session matching: {name}")
        return 1

    sp = sorted(
        matches,
        key=lambda x: x.stat().st_mtime, reverse=True
    )[0]
    with open(sp) as f:
        data = yaml.safe_load(f) or {}

    project  = data.get("project", {})
    log      = data.get("session_log", [])
    modules  = data.get("modules", {})
    convs    = data.get("conventions", {})

    proj_name = project.get("name", name)
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    filename  = f"engram_report_{proj_name}_{timestamp}.md"

    out_dir = Path(output_dir) if output_dir else Path.cwd()
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / filename

    content = _build_markdown(
        proj_name, project, log, modules, convs
    )
    out_path.write_text(content, encoding="utf-8")
    ok(f"Exported: {out_path}")
    info(f"Tasks: {len(log)} | "
         f"Modules: {len(modules)}")
    return 0


def _build_markdown(
    name, project, log, modules, conventions
) -> str:
    """Build markdown report content."""
    ts = datetime.utcnow().isoformat() + "Z"
    lines = [
        f"# ENGRAM Session Report — {name}",
        f"",
        f"**Generated:** {ts}  ",
        f"**Module:** {project.get('module', '?')}  ",
        f"**Tasks:** {len(log)}  ",
        f"",
        f"---",
        f"",
        f"## Project",
        f"",
        f"**Name:** {project.get('name', '?')}  ",
        f"**Path:** {project.get('path', '?')}  ",
        f"",
        f"---",
        f"",
        f"## Module Status",
        f"",
    ]
    for mod_name, mod_data in modules.items():
        if isinstance(mod_data, dict):
            status = mod_data.get("status", "?")
            files  = mod_data.get("files", [])
            lines.append(f"- **{mod_name}**: {status}")
            for f in files:
                lines.append(f"  - `{f}`")

    lines += [
        "",
        "---",
        "",
        "## Conventions Learned",
        "",
    ]
    for key, val in conventions.items():
        if val:
            lines.append(f"- **{key}**: {val}")

    lines += [
        "",
        "---",
        "",
        "## Task History",
        "",
    ]
    for i, entry in enumerate(log, 1):
        ts_raw = entry.get("ts", "")[:16]
        task   = str(
            entry.get("task") or entry.get("event", "")
        )
        quality = entry.get("quality_score")
        q_str  = f" (quality: {quality:.2f})" if quality else ""
        lines.append(f"{i}. `{ts_raw}` — {task}{q_str}")

    lines += ["", "---", "", "*Generated by ENGRAM OS*", ""]
    return "\n".join(lines)


def register(subparsers) -> None:
    """Register export command with argument parser."""
    p = subparsers.add_parser(
        "export",
        help="Export session as a shareable report"
    )
    p.add_argument("name", help="Session name to export")
    p.add_argument("--output", help="Output directory")
    p.add_argument("--format", default="markdown",
                   choices=["markdown"])
    p.set_defaults(func=lambda args: sys.exit(export(
        name=args.name,
        output_dir=args.output,
        fmt=args.format
    )))
